language: ruby
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.12.5
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: jz96HPqztppwVFcy2j7W+82dGfZC4XlQ+8A/Lgzkc2l1Xkdnq8ZeWG+WLpTra5ufRTOFNUTDoFy8Un3zg0UPzRZUnrQciWegYUAodyJXlUECLXT7ARwecaHfJC8cpsKpnKRsn8uD27J9fFPKpYnab4ch7aChmfx5vJuPw2aAJPJWmj/FjwFcOx1E7aAz3LsHbrFd3eT8RL1fQBevuCv4ZFIvJfYl+OxjnlGPdwlW4Rx8ZUIfLwa9PfRBKKsWhyYYipPwhsimPbqPd2VszkVDvBIfFikAIRRLAiP1Vx4DbNhO7VQkqtdYi8DRrHAEJ3tJEfA5+UGB/jVAzRqSKAHde8PDvjNbrPtepK+891Laly5r7/BjtAq5eyyVmQYDAvvZYZseaclUcu2JqdA1H3A0+8xb17QWTQbdNs0016OBdznDQuPGDo6GO0iKrlFkSYoadee6l1DWEnfLzMz7CPEr/mnFcJL4gPGkE5GYwWTN72yG5Y+ryzmoKkWwr/TcBKITDCGRoHS7BBrzxzxwVWAUqojnsM4F+LcWV47V4/bwFAVXt0oPPGak7RVR4Fvh42Mpjik+JS31QeEKZDB0m/17w/wfWjsgYw2xyJXznu1nr+RMrrZVPfAC9Qpq/j0zQlTWif+81G+CjT/ENDCRX9++waAXurY+VZ0STbfMEJNYxdU=
  gem: send_grid_mailer
  on:
    tags: true
    repo: platanus/send_grid_mailer
